# Generated by Django 3.0.3 on 2022-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='Name of Category')),
                ('category_summary', models.CharField(default='', max_length=150, verbose_name='Something About The Range Of Products')),
                ('category_card_image', models.ImageField(upload_to='category_card_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50, verbose_name='Name of Product')),
                ('product_summary', models.CharField(default='', max_length=150, verbose_name='Something About The Products')),
                ('product_card_image', models.ImageField(upload_to='product_card_images')),
            ],
        ),
    ]
