# Generated by Django 4.1 on 2023-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='message',
            field=models.CharField(default='', max_length=1000, verbose_name='Write A Message Here'),
        ),
    ]
