# Generated by Django 4.1 on 2023-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_category_category_herosection_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
